workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Install CocoaPods (genera Podfile.lock)
        script: |
          cd ios
          pod install --repo-update
          cd ..
          
      - name: Build iOS IPA
        script: flutter build ipa --release
    
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Podfile.lock
      - ios/Podfile
    
    publishing:
      email:
        recipients:
          - danielbernardograset@gmail.com
