// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWgm5k3ndyG0SDUQOBqf-6OWwe4djFL1Y',
    appId: '1:834754390012:web:f4eee5e1ac7d2499bbf479',
    messagingSenderId: '834754390012',
    projectId: 'memoriumm-de924',
    authDomain: 'memoriumm-de924.firebaseapp.com',
    storageBucket: 'memoriumm-de924.firebasestorage.app',
    measurementId: 'G-GG58XX1L39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdXhGA0DO0ZD9rzqn3F1-YLoh3lsip-xQ',
    appId: '1:834754390012:android:2bd1ff7b03711e53bbf479',
    messagingSenderId: '834754390012',
    projectId: 'memoriumm-de924',
    storageBucket: 'memoriumm-de924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYU8YjLeFtIqE-63AJmDO8j22Er5P5S0g',
    appId: '1:834754390012:ios:2e69b750e7241edabbf479',
    messagingSenderId: '834754390012',
    projectId: 'memoriumm-de924',
    storageBucket: 'memoriumm-de924.firebasestorage.app',
    iosBundleId: 'db.memorium.memorium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYU8YjLeFtIqE-63AJmDO8j22Er5P5S0g',
    appId: '1:834754390012:ios:2e69b750e7241edabbf479',
    messagingSenderId: '834754390012',
    projectId: 'memoriumm-de924',
    storageBucket: 'memoriumm-de924.firebasestorage.app',
    iosBundleId: 'db.memorium.memorium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWgm5k3ndyG0SDUQOBqf-6OWwe4djFL1Y',
    appId: '1:834754390012:web:c4ea273f361711dfbbf479',
    messagingSenderId: '834754390012',
    projectId: 'memoriumm-de924',
    authDomain: 'memoriumm-de924.firebaseapp.com',
    storageBucket: 'memoriumm-de924.firebasestorage.app',
    measurementId: 'G-TH1BGBMHKB',
  );

}