// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsqAKqG9uUNjv62PR0wQ4ZBUQhexXuAg',
    appId: '1:511117194437:web:7de4e0ce9678a5e1ff2cac',
    messagingSenderId: '511117194437',
    projectId: 'memoriumm-globalcatdev',
    authDomain: 'memoriumm-globalcatdev.firebaseapp.com',
    storageBucket: 'memoriumm-globalcatdev.firebasestorage.app',
    measurementId: 'G-C1Q5L7Y58B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK8tLTvYQdi_m5_YfgoY4Wud37Su5Zva0',
    appId: '1:511117194437:android:fd3be8127d6b9c35ff2cac',
    messagingSenderId: '511117194437',
    projectId: 'memoriumm-globalcatdev',
    storageBucket: 'memoriumm-globalcatdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8WMrwYmvuICiuqnzzbATl7O7RhOH0l5w',
    appId: '1:511117194437:ios:0198b367eee26506ff2cac',
    messagingSenderId: '511117194437',
    projectId: 'memoriumm-globalcatdev',
    storageBucket: 'memoriumm-globalcatdev.firebasestorage.app',
    iosBundleId: 'db.memorium.memorium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8WMrwYmvuICiuqnzzbATl7O7RhOH0l5w',
    appId: '1:511117194437:ios:0198b367eee26506ff2cac',
    messagingSenderId: '511117194437',
    projectId: 'memoriumm-globalcatdev',
    storageBucket: 'memoriumm-globalcatdev.firebasestorage.app',
    iosBundleId: 'db.memorium.memorium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjsqAKqG9uUNjv62PR0wQ4ZBUQhexXuAg',
    appId: '1:511117194437:web:4c0632d0e4030481ff2cac',
    messagingSenderId: '511117194437',
    projectId: 'memoriumm-globalcatdev',
    authDomain: 'memoriumm-globalcatdev.firebaseapp.com',
    storageBucket: 'memoriumm-globalcatdev.firebasestorage.app',
    measurementId: 'G-D2KP7PBKGE',
  );
}
