# Utilitzem la variable d'entorn de Flutter directament
flutter_root = ENV['FLUTTER_ROOT'] || File.join('..', '..', 'flutter')
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
